spring:
  application:
    name: zuul-server

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api
#  routes:
#    account-service:
#      path: /accounts/**
#      serviceId: WEB-APPLICATION-ACCOUNT
  host:
    socket-timeout-millis: 30000
